[package]
name = "penguin-config"
version = "0.1.0"
authors = ["Henrik Nilsson <github.com/Henrik-N>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
derive = ["penguin-config-derive"]

[dependencies.penguin-config-derive]
git = "https://github.com/Henrik-N/penguin-config-derive"
optional = true


# ----- Serializiation ----- #
[dependencies.serde]
version = "1.0"
features = ["serde_derive"]
[dependencies.serde_json]
version = "1.0"

